version: "3"

services:
  mattermost-db:
    image: postgres:14
    container_name: mattermost-db
    restart: always
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - mattermost-db-data:/var/lib/postgresql/data
    networks:
      - proxy-tier

  mattermost-app:
    image: custom-mattermost:backup-2025061701
    container_name: mattermost-app
    restart: always
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@mattermost-db:5432/mattermost?sslmode=disable
      - MM_SERVICESETTINGS_SITEURL=https://redmineqadb.soosanint.com/mattermost
      - MM_SERVICESETTINGS_LISTENADDRESS=:8065
    depends_on:
      - mattermost-db
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-logs:/mattermost/logs
      - mattermost-config:/mattermost/config
    networks:
      - proxy-tier
    ports:
      - "8065:8065"

volumes:
  mattermost-db-data:
  mattermost-data:
  mattermost-logs:
  mattermost-config:

networks:
  proxy-tier:
    external: true
